name: sample workflow
on:
  workflow_dispatch: 
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Maven Build
        run: mvn clean package
      - name: login to ecr
        run: | 
          aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin 687098277845.dkr.ecr.ap-south-2.amazonaws.com
      - name: buil the docker image 
        run: |
          docker build -t test .
          docker tag test:latest 687098277845.dkr.ecr.ap-south-2.amazonaws.com/test:latest
      - name: push the image to ecr
        run: |
           docker push 687098277845.dkr.ecr.ap-south-2.amazonaws.com/test:${{ github.sha }}
           docker push 687098277845.dkr.ecr.ap-south-2.amazonaws.com/test:latest
      
